### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by EmeraldSnorlax**
Fixes [this](https://www.youtube.com/watch?v=dlKle4IOnZU)

### CODE REVIEW

**Comment by EmeraldSnorlax** [comment]
~~oh and i think all contributors need to agree on this~~

**Comment by SoNothingMC** [comment]
I'm not sure if we could actually add a license to the entire project though... since the bigrat image is still ARR'd under the original creator

Maybe we could license AGPL to *just* the code?

**Comment by EmeraldSnorlax** [comment]
that is what a software license is for
add a seperate copyright for the image in the readme / on the site

obligatory ianal

**Comment by EmeraldSnorlax** [comment]
approval from all contributors regarding these changes are needed before merging

**Review by bigratenthusiast — APPROVED** [review]
I hereby approve.

**Review by humboldt123 — APPROVED** [review]

**Review by SoNothingMC — APPROVED** [review]

**Review by d1snin — APPROVED** [review]

**Comment by EmeraldSnorlax** [comment]
I approve of all changes since my last commit.

**Pull request merged**
