### PR TITLE
Embed warnings

### PR DESCRIPTION
**Pull request by EmeraldSnorlax**
Replaces the embed in services with a safer version

embed-warning

### CODE REVIEW

**Comment by EmeraldSnorlax** [comment]
you *should* just be able to accept all incoming changes to solve this merge conflict

**Comment by humboldt123** [comment]
What purpose does embed-warning.xcf serve?

**Comment by EmeraldSnorlax** [comment]
> What purpose does embed-warning.xcf serve?

It is the GIMP source file, should anyone wish to edit it

**Comment by EmeraldSnorlax** [comment]
merge conflict is fixed

**Comment by humboldt123** [comment]
Thanks!

**Pull request merged**
